// Generated by tools/bootdex/build_bootdex.py; do not edit.
// Reviewed source: tools/bootdex/api19-system-resources.json
// Table SHA-256: 66141bfeb1e3f35d140c5fb005e0f59a7d2f5ae8b4a9fc3893c1fbe9e28fa1a1
#pragma once

#include <cstdint>
#include <string_view>

namespace ogplay::runtime::android_intrinsics {

struct ReviewedSystemResource {
  std::uint32_t id;
  std::string_view name;
  const char *string_value;
  std::int32_t integer_value;
};

inline constexpr ReviewedSystemResource kSystemResources[] = {
    {0x0104011cU, "db_default_journal_mode", "DELETE", 0},
    {0x0104011dU, "db_default_sync_mode", "FULL", 0},
    {0x0104011eU, "db_wal_sync_mode", "FULL", 0},
    {0x010e0038U, "db_connection_pool_size", nullptr, 4},
    {0x010e0039U, "db_journal_size_limit", nullptr, 524288},
    {0x010e003aU, "db_wal_autocheckpoint", nullptr, 100},
    {0x010e003eU, "config_cursorWindowSize", nullptr, 2048},
};

[[nodiscard]] inline const ReviewedSystemResource *
FindSystemResource(const std::uint32_t id) {
  for (const auto &resource : kSystemResources)
    if (resource.id == id) return &resource;
  return nullptr;
}

} // namespace ogplay::runtime::android_intrinsics
