#!/usr/bin/env python3
"""Generate review-ready per-class android intrinsic declaration skeletons."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MEMBER_PATTERN = re.compile(r"^([^(]+)(\(.*\))(.+)$")
PRIMITIVE_SHORTIES = frozenset("VZBSCIJFD")


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symbol(descriptor: str) -> str:
    body = re.sub(r"[^A-Za-z0-9]", "_", descriptor[1:-1]).strip("_")
    return f"Declare_{body}"


def load_members(gaps: dict | None, survey: dict | None
                 ) -> list[tuple[str, str, int]]:
    members: dict[tuple[str, str], int] = {}
    if survey is not None:
        for entry in survey.get("missing_members", []):
            key = (entry["class"], entry["member"])
            members[key] = max(members.get(key, 0), int(entry.get("hits", 0)))
    if gaps is not None:
        for owner, entry in gaps.get("runtime", {}).items():
            for member in entry.get("methods", []):
                members.setdefault((owner, member), 0)
    return sorted(((owner, member, hits)
                   for (owner, member), hits in members.items()),
                  key=lambda row: (-row[2], row[0], row[1]))


def render_method(member: str) -> str | None:
    match = MEMBER_PATTERN.match(member)
    if match is None:
        return None
    name, arguments, result = match.groups()
    signature = arguments + result
    if result == "Ljava/lang/String;":
        factory = "PlaceholderString()"
    elif result in PRIMITIVE_SHORTIES:
        factory = f"NeutralHandler('{result}')"
    else:
        return None
    return (f"    builder.VirtualMethod({cpp_string(name)}, {cpp_string(signature)}, "
            f"{factory});")


def render_surface(surface: dict, selected: list[str]) -> str:
    if surface.get("schema") != 1:
        raise ValueError("API-19 surface schema 1 expected")
    classes = surface.get("classes", [])
    if selected:
        wanted = set(selected)
        classes = [entry for entry in classes
                   if entry["descriptor"] in wanted]
        missing = wanted - {entry["descriptor"] for entry in classes}
        if missing:
            raise ValueError("surface classes not found: " + ", ".join(sorted(missing)))
    lines = [
        "// Generated by tools/dexvm_stub_gen.py from pinned API-19 sources.",
        "// Replace explicit unimplemented methods with reviewed handlers.",
        "#include <utility>",
        "",
        '#include "ogplay/runtime/dexvm/intrinsic_builder.h"',
        "",
        "namespace ogplay::runtime::dexvm::generated {",
    ]
    for entry in classes:
        owner = entry["descriptor"]
        lines += ["", f"IntrinsicClassDecl {symbol(owner)}() {{"]
        interfaces = entry.get("interfaces", [])
        interface_args = "{" + ", ".join(cpp_string(item) for item in interfaces) + "}"
        if entry["kind"] == "interface":
            factory = (f"IntrinsicClassBuilder::Interface({cpp_string(owner)}"
                       + (f", {interface_args}" if interfaces else "") + ")")
        elif entry.get("superclass") is None:
            factory = f"IntrinsicClassBuilder::RootClass({cpp_string(owner)})"
        else:
            factory = (f"IntrinsicClassBuilder::Class({cpp_string(owner)}, "
                       f"{cpp_string(entry['superclass'])}"
                       + (f", {interface_args}" if interfaces else "") + ")")
        lines.append(f"    auto builder = {factory};")
        for field in entry.get("fields", []):
            static = "static" in field.get("modifiers", [])
            method = "BoundStaticField" if static else "BoundInstanceField"
            variable = re.sub(r"[^A-Za-z0-9_]", "_", field["name"])
            lines.append(
                f"    [[maybe_unused]] const auto field_{variable} = builder.{method}("
                f"{cpp_string(field['name'])}, {cpp_string(field['descriptor'])});")
        for method in entry.get("methods", []):
            name = method["name"]
            descriptor = method["descriptor"]
            modifiers = set(method.get("modifiers", []))
            if name == "<init>":
                declaration = "UnimplementedConstructor"
                arguments = cpp_string(descriptor)
            elif "static" in modifiers:
                declaration = "UnimplementedStatic"
                arguments = f"{cpp_string(name)}, {cpp_string(descriptor)}"
            elif "final" in modifiers:
                declaration = "UnimplementedFinal"
                arguments = f"{cpp_string(name)}, {cpp_string(descriptor)}"
            else:
                declaration = "UnimplementedVirtual"
                arguments = f"{cpp_string(name)}, {cpp_string(descriptor)}"
            lines.append(f"    builder.{declaration}({arguments});")
        lines += ["    return std::move(builder).Build();", "}"]
    lines += ["", "}  // namespace ogplay::runtime::dexvm::generated"]
    return "\n".join(lines) + "\n"


def render(gaps: dict | None, survey: dict | None, reached_only: bool,
           limit: int) -> str:
    roles: dict[str, str] = {}
    if gaps is not None:
        roles.update({owner: entry["role"]
                      for owner, entry in gaps.get("link_blocking", {}).items()})

    members = load_members(gaps, survey)
    if reached_only:
        members = [row for row in members if row[2] > 0]
    if limit > 0:
        members = members[:limit]

    by_owner: dict[str, list[str]] = {}
    decisions: list[str] = []
    for owner, member, hits in members:
        rendered = render_method(member)
        if rendered is None:
            decisions.append(f"// {owner}->{member}" +
                             (f" (hits {hits})" if hits else ""))
            continue
        by_owner.setdefault(owner, []).append(rendered)

    owners = sorted(set(roles) | set(by_owner))
    lines = [
        "// Generated by tools/dexvm_stub_gen.py; review before adding.",
        '#include "catalog.h"',
        "",
        "namespace ogplay::runtime::android_intrinsics {",
    ]
    for owner in owners:
        lines += ["", f"Decl {symbol(owner)}(const Context& context) {{",
                  "    static_cast<void>(context);",
                  ]
        role = roles.get(owner, "class")
        if role == "interface":
            lines.append(
                f"    auto builder = dx::IntrinsicClassBuilder::Interface({cpp_string(owner)});")
        else:
            lines.append(
                f"    auto builder = dx::IntrinsicClassBuilder::Class({cpp_string(owner)});")
            if role == "both":
                lines.append("    // review: referenced as both class and interface")
        lines.extend(by_owner.get(owner, []))
        lines += ["    return std::move(builder).Build();", "}"]
    lines += ["", "}  // namespace ogplay::runtime::android_intrinsics"]
    if decisions:
        lines += ["", "// Needs a real decision; reference-return placeholders are",
                  "// not generated because a neutral object would be dishonest."]
        lines.extend(decisions)
    return "\n".join(lines) + "\n"


def self_test() -> int:
    gaps = {
        "schema": 2,
        "link_blocking": {
            "Landroid/example/Foo;": {"role": "class"},
        },
        "runtime": {
            "Landroid/example/Foo;": {
                "methods": ["reset()V", "count()I", "name()Ljava/lang/String;",
                            "object()Ljava/lang/Object;"]
            }
        },
    }
    output = render(gaps, None, False, 0)
    assert "Decl Declare_android_example_Foo(const Context& context)" in output
    assert "NeutralHandler('V')" in output
    assert "NeutralHandler('I')" in output
    assert "PlaceholderString()" in output
    assert "object()Ljava/lang/Object;" in output
    assert "android.widget." not in output
    assert ".Register(" not in output
    assert "IntrinsicClassBuilder::Class" in output
    assert ".VirtualMethod(" in output
    surface = {
        "schema": 1,
        "classes": [{
            "descriptor": "Ljava/example/Typed;", "kind": "class",
            "superclass": "Ljava/lang/Object;", "interfaces": [],
            "fields": [
                {"name": "value", "descriptor": "I", "modifiers": ["private"]},
                {"name": "count", "descriptor": "I", "modifiers": ["static"]},
            ],
            "methods": [
                {"name": "<init>", "descriptor": "(I)V", "modifiers": ["public"]},
                {"name": "get", "descriptor": "()I", "modifiers": ["public", "final"]},
            ],
        }],
    }
    typed = render_surface(surface, ["Ljava/example/Typed;"])
    assert "BoundInstanceField" in typed
    assert "BoundStaticField" in typed
    assert "UnimplementedConstructor" in typed
    assert "UnimplementedFinal" in typed
    print("dexvm stub generator self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gaps", type=Path)
    parser.add_argument("--survey", type=Path)
    parser.add_argument("--surface", type=Path)
    parser.add_argument("--class", dest="classes", action="append", default=[])
    parser.add_argument("--reached-only", action="store_true")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--self-test", action="store_true")
    arguments = parser.parse_args()
    if arguments.self_test:
        return self_test()
    if arguments.surface is not None:
        surface = json.loads(arguments.surface.read_text(encoding="utf-8"))
        try:
            print(render_surface(surface, arguments.classes), end="")
        except ValueError as error:
            parser.error(str(error))
        return 0
    if arguments.gaps is None and arguments.survey is None:
        parser.error("pass --surface or --gaps and/or --survey")
    gaps = json.loads(arguments.gaps.read_text(encoding="utf-8")) \
        if arguments.gaps else None
    survey = json.loads(arguments.survey.read_text(encoding="utf-8")) \
        if arguments.survey else None
    if gaps is not None and gaps.get("schema") != 2:
        parser.error("gap report schema 2 expected; regenerate the report")
    print(render(gaps, survey, arguments.reached_only, arguments.limit), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
