#!/usr/bin/env python3
"""Generate review-ready per-class android intrinsic declaration skeletons."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MEMBER_PATTERN = re.compile(r"^([^(]+)(\(.*\))(.+)$")
PRIMITIVE_SHORTIES = frozenset("VZBSCIJFD")


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def symbol(descriptor: str) -> str:
    body = re.sub(r"[^A-Za-z0-9]", "_", descriptor[1:-1]).strip("_")
    return f"Declare_{body}"


def load_members(gaps: dict | None, survey: dict | None
                 ) -> list[tuple[str, str, int]]:
    members: dict[tuple[str, str], int] = {}
    if survey is not None:
        for entry in survey.get("missing_members", []):
            key = (entry["class"], entry["member"])
            members[key] = max(members.get(key, 0), int(entry.get("hits", 0)))
    if gaps is not None:
        for owner, entry in gaps.get("runtime", {}).items():
            for member in entry.get("methods", []):
                members.setdefault((owner, member), 0)
    return sorted(((owner, member, hits)
                   for (owner, member), hits in members.items()),
                  key=lambda row: (-row[2], row[0], row[1]))


def render_method(member: str) -> str | None:
    match = MEMBER_PATTERN.match(member)
    if match is None:
        return None
    name, arguments, result = match.groups()
    signature = arguments + result
    if result == "Ljava/lang/String;":
        factory = "PlaceholderString()"
    elif result in PRIMITIVE_SHORTIES:
        factory = f"NeutralHandler('{result}')"
    else:
        return None
    return (f"    builder.Virtual({cpp_string(name)}, {cpp_string(signature)}, "
            f"{factory});")


def render(gaps: dict | None, survey: dict | None, reached_only: bool,
           limit: int) -> str:
    roles: dict[str, str] = {}
    if gaps is not None:
        roles.update({owner: entry["role"]
                      for owner, entry in gaps.get("link_blocking", {}).items()})

    members = load_members(gaps, survey)
    if reached_only:
        members = [row for row in members if row[2] > 0]
    if limit > 0:
        members = members[:limit]

    by_owner: dict[str, list[str]] = {}
    decisions: list[str] = []
    for owner, member, hits in members:
        rendered = render_method(member)
        if rendered is None:
            decisions.append(f"// {owner}->{member}" +
                             (f" (hits {hits})" if hits else ""))
            continue
        by_owner.setdefault(owner, []).append(rendered)

    owners = sorted(set(roles) | set(by_owner))
    lines = [
        "// Generated by tools/dexvm_stub_gen.py; review before adding.",
        '#include "catalog.h"',
        "",
        "namespace ogplay::runtime::android_intrinsics {",
    ]
    for owner in owners:
        lines += ["", f"Decl {symbol(owner)}(const Context& context) {{",
                  "    static_cast<void>(context);",
                  f"    dx::IntrinsicClassBuilder builder({cpp_string(owner)});"]
        role = roles.get(owner, "class")
        if role == "interface":
            lines.append("    builder.MarkInterface();")
        else:
            lines.append('    builder.Super("Ljava/lang/Object;");')
            if role == "both":
                lines.append("    // review: referenced as both class and interface")
        lines.extend(by_owner.get(owner, []))
        lines += ["    return std::move(builder).Build();", "}"]
    lines += ["", "}  // namespace ogplay::runtime::android_intrinsics"]
    if decisions:
        lines += ["", "// Needs a real decision; reference-return placeholders are",
                  "// not generated because a neutral object would be dishonest."]
        lines.extend(decisions)
    return "\n".join(lines) + "\n"


def self_test() -> int:
    gaps = {
        "schema": 2,
        "link_blocking": {
            "Landroid/example/Foo;": {"role": "class"},
        },
        "runtime": {
            "Landroid/example/Foo;": {
                "methods": ["reset()V", "count()I", "name()Ljava/lang/String;",
                            "object()Ljava/lang/Object;"]
            }
        },
    }
    output = render(gaps, None, False, 0)
    assert "Decl Declare_android_example_Foo(const Context& context)" in output
    assert "NeutralHandler('V')" in output
    assert "NeutralHandler('I')" in output
    assert "PlaceholderString()" in output
    assert "object()Ljava/lang/Object;" in output
    assert "android.widget." not in output
    assert ".Register(" not in output
    print("dexvm stub generator self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gaps", type=Path)
    parser.add_argument("--survey", type=Path)
    parser.add_argument("--reached-only", action="store_true")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--self-test", action="store_true")
    arguments = parser.parse_args()
    if arguments.self_test:
        return self_test()
    if arguments.gaps is None and arguments.survey is None:
        parser.error("pass --gaps and/or --survey")
    gaps = json.loads(arguments.gaps.read_text(encoding="utf-8")) \
        if arguments.gaps else None
    survey = json.loads(arguments.survey.read_text(encoding="utf-8")) \
        if arguments.survey else None
    if gaps is not None and gaps.get("schema") != 2:
        parser.error("gap report schema 2 expected; regenerate the report")
    print(render(gaps, survey, arguments.reached_only, arguments.limit), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
