#!/usr/bin/env python3
"""Generate the immutable API19 virtual keyboard native lookup data."""
from __future__ import annotations

import argparse
import ast
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP = ROOT / ".local/aosp/framework/base/data/keyboards/Virtual.kcm"
KEYS = ROOT / ".local/aosp/framework/base/core/java/android/view/KeyEvent.java"
OUTPUT = ROOT / "src/runtime/integration/dexvm_android/virtual_keymap.inc"
MODIFIERS = {"base": 0, "shift": 1, "alt": 2, "ctrl": 0x1000,
             "meta": 0x10000, "capslock": 0x100000, "numlock": 0x200000}


def generate() -> str:
    source = MAP.read_text(encoding="utf-8")
    codes = {name: int(value) for name, value in re.findall(
        r"public static final int KEYCODE_(\w+)\s*=\s*(\d+)\s*;",
        KEYS.read_text(encoding="utf-8"))}
    if not re.search(r"^type FULL$", source, re.M):
        raise ValueError("expected the API19 FULL virtual keyboard")
    keys = []
    rules = []
    for name, block in re.findall(r"^key (\w+) \{\n(.*?)^\}", source, re.M | re.S):
        code = codes[name]
        label = number = 0
        behaviors = []
        for line in block.splitlines():
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            props, body = line.split(":", 1)
            value = re.fullmatch(r"\s*('(?:\\.|[^'\\])*'|none)?\s*(?:fallback\s+(\w+))?\s*", body)
            if not value:
                raise ValueError(f"unreviewed key behavior: {name}: {line}")
            literal, fallback = value.groups()
            character = 0 if literal in (None, "none") else ord(ast.literal_eval(literal))
            if character > 0xffff:
                raise ValueError("KCM characters must fit UTF-16")
            for prop in props.strip().split(","):
                prop = prop.strip()
                if prop == "label":
                    label = character
                elif prop == "number":
                    number = character
                else:
                    meta = 0
                    for modifier in prop.split("+"):
                        meta |= MODIFIERS[modifier]
                    if any(row[1] == meta for row in behaviors):
                        raise ValueError(f"duplicate behavior: {name}: {prop}")
                    # AOSP Parser::parseKeyProperty prepends each behavior.
                    behaviors.insert(0, (code, meta, character, codes[fallback] if fallback else 0))
        if not number:
            digit = symbol = 0
            for _, _, ch, _ in behaviors:
                if ord('0') <= ch <= ord('9'):
                    digit = ch
                elif ch and chr(ch) in "()#*-+,.':;/":
                    symbol = ch
            number = digit or symbol  # AOSP Parser::finishKey.
        keys.append((code, label, number))
        rules.extend(behaviors)
    if len({row[0] for row in keys}) != len(keys):
        raise ValueError("duplicate key declaration")
    keys.sort()
    lines = ["// Generated by tools/generate_virtual_keymap.py; do not edit.",
             "// AOSP android-4.4.4 Virtual.kcm data, Copyright (C) 2010 The Android Open Source Project.",
             "// SPDX-License-Identifier: Apache-2.0"]
    for path in (MAP, KEYS):
        lines.append(f"// {path.relative_to(ROOT)} sha256={hashlib.sha256(path.read_bytes()).hexdigest()}")
    lines += [f"constexpr std::array<VirtualKey, {len(keys)}> kVirtualKeys{{{{"]
    lines += [f"    {{{code}, {label}, {number}}}," for code, label, number in keys]
    lines += ["}};", f"constexpr std::array<VirtualKeyBehavior, {len(rules)}> kVirtualKeyBehaviors{{{{"]
    lines += [f"    {{{code}, 0x{meta:x}, {ch}, {fallback}}}," for code, meta, ch, fallback in rules]
    lines += ["}};", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("virtual keyboard data differs from AOSP inputs")
    else:
        OUTPUT.write_text(text, encoding="utf-8")
    print("API19 virtual keyboard data verified" if args.check else "Generated API19 virtual keyboard data")


if __name__ == "__main__":
    main()
