#!/usr/bin/env python3
"""Generate the API-19 android.opengl Java surface consumed by DexVM."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from dexvm_api19_surface import parse_java, split_top_level, strip_source

CLASSES = ("GLES10", "GLES10Ext", "GLES11", "GLES11Ext", "GLES20",
           "GLUtils", "GLU")


def constant_values(text: str) -> dict[str, int]:
    clean = strip_source(text)
    values: dict[str, int] = {}
    declarations = re.findall(
        r"public\s+static\s+final\s+int\s+([^;]+);", clean)
    pending: list[tuple[str, str]] = []
    for declaration in declarations:
        for variable in split_top_level(declaration):
            if "=" in variable:
                name, expression = variable.split("=", 1)
                pending.append((name.strip(), expression.strip()))
    while pending:
        next_pending: list[tuple[str, str]] = []
        progressed = False
        for name, expression in pending:
            expression = re.sub(r"(?<=\w)[lL]\b", "", expression)
            expression = expression.replace("~0", "-1")
            try:
                value = int(eval(expression, {"__builtins__": {}}, values))
            except (NameError, SyntaxError, TypeError):
                next_pending.append((name, expression))
                continue
            value &= 0xffffffff
            if value >= 0x80000000:
                value -= 0x100000000
            values[name] = value
            progressed = True
        if not progressed:
            names = ", ".join(name for name, _ in next_pending)
            raise ValueError(f"cannot evaluate Java GLES constants: {names}")
        pending = next_pending
    return values


def render(source_root: Path) -> str:
    available = {
        path.relative_to(source_root).with_suffix("").as_posix().replace("/", ".")
        for path in source_root.rglob("*.java")
    }
    available.update({"java.lang.Object", "java.lang.String",
                      "java.lang.Class", "java.lang.Throwable"})
    lines = [
        "// Generated by tools/generate_java_gles_surface.py from the pinned",
        "// Android 4.4.4_r2.0.1 AOSP sources. Do not edit by hand.",
        "namespace generated_java_gles {",
        "struct MethodSpec final { const char* name; const char* descriptor; };",
        "struct ConstantSpec final { const char* name; std::int32_t value; };",
    ]
    for class_name in CLASSES:
        path = source_root / "android" / "opengl" / f"{class_name}.java"
        text = path.read_text(encoding="utf-8")
        shape = parse_java(text, path.as_posix(), available)
        methods = [method for method in shape["methods"]
                   if "public" in method["modifiers"] and
                   "static" in method["modifiers"] and
                   method["name"] != "<init>"]
        values = constant_values(text)
        lines.append(f"inline constexpr MethodSpec k{class_name}Methods[] = {{")
        for method in methods:
            lines.append(f'    {{"{method["name"]}", "{method["descriptor"]}"}},')
        lines.append("};")
        if values:
            lines.append(f"inline constexpr ConstantSpec k{class_name}Constants[] = {{")
            for name, value in sorted(values.items()):
                lines.append(f'    {{"{name}", {value}}},')
            lines.append("};")
        else:
            lines.append(f"inline constexpr std::array<ConstantSpec, 0> k{class_name}Constants{{}};")
    lines.append("}  // namespace generated_java_gles")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render(arguments.source_root)
    if arguments.check:
        if arguments.output.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"Java GLES surface is stale: {arguments.output}")
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
