if(NOT EXISTS "${WEBUI_ROOT}/manifest.json" OR NOT EXISTS "${WEBUI_ROOT}/index.html")
    message(FATAL_ERROR "GUI Web UI missing; build webui with npm ci and npm run build")
endif()
file(READ "${WEBUI_ROOT}/manifest.json" manifest)
string(JSON count LENGTH "${manifest}" files)
if(count LESS 3)
    message(FATAL_ERROR "Incomplete GUI manifest")
endif()
math(EXPR last "${count} - 1")
foreach(i RANGE 0 ${last})
    string(JSON path GET "${manifest}" files ${i} path)
    string(JSON expected GET "${manifest}" files ${i} sha256)
    if(path MATCHES "[/\\\\:]" OR path MATCHES "^\\.")
        message(FATAL_ERROR "Unsafe GUI artifact path")
    endif()
    if(NOT EXISTS "${WEBUI_ROOT}/${path}")
        message(FATAL_ERROR "Missing GUI artifact: ${path}")
    endif()
    file(SHA256 "${WEBUI_ROOT}/${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "GUI artifact hash mismatch: ${path}")
    endif()
endforeach()
