# Keep the pinned submodule clean. Generate a checked, x64-only diagnostic extension.
set(_dyn_src "${PROJECT_SOURCE_DIR}/third_party/dynarmic/src")
set(_dyn_diag "${CMAKE_BINARY_DIR}/generated/dynarmic-diagnostics")
file(READ "${_dyn_src}/dynarmic/interface/A32/a32.h" _dyn_header)
file(READ "${_dyn_src}/dynarmic/backend/x64/a32_interface.cpp" _dyn_impl)
foreach(_needle IN ITEMS "    void ClearCache();" "    struct Impl;")
    string(FIND "${_dyn_header}" "${_needle}" _found)
    if(_found LESS 0)
        message(FATAL_ERROR "Dynarmic diagnostic header no longer matches pinned source")
    endif()
endforeach()
string(FIND "${_dyn_impl}" "                block_of_code.ClearCache();" _found)
if(_found LESS 0)
    message(FATAL_ERROR "Dynarmic cache invalidation changed; review diagnostic extension")
endif()
string(REPLACE "    void ClearCache();" "    void ClearCache();\n    std::array<std::uint64_t, 3> CacheStatistics() const;" _dyn_header "${_dyn_header}")
string(REPLACE "struct Jit::Impl {" "struct Jit::Impl {\n    friend class Jit;" _dyn_impl "${_dyn_impl}")
string(REPLACE "    A32JitState jit_state;" "    std::uint64_t cache_flushes{};\n    A32JitState jit_state;" _dyn_impl "${_dyn_impl}")
string(REPLACE "                block_of_code.ClearCache();" "                ++cache_flushes;\n                block_of_code.ClearCache();" _dyn_impl "${_dyn_impl}")
string(APPEND _dyn_impl "\nnamespace Dynarmic::A32 {\nstd::array<std::uint64_t, 3> Jit::CacheStatistics() const {\n return {impl->block_of_code.GetTotalCodeSize(), impl->block_of_code.GetTotalCodeSize() - impl->block_of_code.SpaceRemaining(), impl->cache_flushes};\n}\n}\n")
file(MAKE_DIRECTORY "${_dyn_diag}/dynarmic/interface/A32")
file(WRITE "${_dyn_diag}/header.in" "${_dyn_header}")
configure_file("${_dyn_diag}/header.in" "${_dyn_diag}/dynarmic/interface/A32/a32.h" COPYONLY)
file(WRITE "${_dyn_diag}/source.in" "${_dyn_impl}")
configure_file("${_dyn_diag}/source.in" "${_dyn_diag}/a32_interface.cpp" COPYONLY)
get_target_property(_dyn_sources dynarmic SOURCES)
set(_dyn_replaced FALSE)
foreach(_source IN LISTS _dyn_sources)
    if(_source MATCHES "backend/x64/a32_interface.cpp$")
        list(REMOVE_ITEM _dyn_sources "${_source}")
        set(_dyn_replaced TRUE)
    endif()
endforeach()
if(NOT _dyn_replaced)
    message(FATAL_ERROR "Dynarmic x64 source missing for diagnostic extension")
endif()
list(APPEND _dyn_sources "${_dyn_diag}/a32_interface.cpp")
set_property(TARGET dynarmic PROPERTY SOURCES "${_dyn_sources}")
target_include_directories(dynarmic BEFORE PUBLIC "$<BUILD_INTERFACE:${_dyn_diag}>")
target_compile_definitions(dynarmic PUBLIC OGPLAY_DYNARMIC_CACHE_STATS=1)
