#include <doctest/doctest.h>
#include "ogplay/gles/atc.h"
#include <array>
#include <limits>
#include <ostream>
#include <stdexcept>
#include <string_view>
namespace {
std::vector<std::byte> Hex(std::string_view text) {
    std::vector<std::byte> bytes;
    const auto digit = [](char c) {return c <= '9' ? c-'0' : c-'a'+10;};
    for (std::size_t i=0;i<text.size();i+=2)
        bytes.push_back(static_cast<std::byte>(digit(text[i])*16+digit(text[i+1])));
    return bytes;
}
}
// Generated by pinned AMD RGB decoder + verbatim codec_atc.cpp alpha methods.
// Source and oracle provenance: third_party/compressonator/README.md.
TEST_CASE("ATC decoder matches independent AMD color and alpha vectors") {
    struct Vector { std::uint32_t format;std::string_view input,rgba; };
    const Vector vectors[]{
        {0x8c92U, "007ce007e4e4e4e4", "ff0000ff9f5f00ff5f9f00ff00ff00ffff0000ff9f5f00ff5f9f00ff00ff00ffff0000ff9f5f00ff5f9f00ff00ff00ffff0000ff9f5f00ff5f9f00ff00ff00ff"},
        {0x8c92U, "e08300f8e4e4e4e4", "000000ff00ff00ff00ff00ffff0000ff000000ff00ff00ff00ff00ffff0000ff000000ff00ff00ff00ff00ffff0000ff000000ff00ff00ff00ff00ffff0000ff"},
        {0x8c93U, "1032547698badcfe007ce007e4e4e4e4", "ff0000009f5f00115f9f002200ff0033ff0000449f5f00555f9f006600ff0077ff0000889f5f00995f9f00aa00ff00bbff0000cc9f5f00dd5f9f00ee00ff00ff"},
        {0x87eeU, "fac8fa8888c6fa00007ce007e4e4e4e4", "ff0000f39f5f00cf5f9f00ec00ff00e5ff0000fa9f5f00c85f9f00f300ff00e5ff0000d69f5f00fa5f9f00ec00ff00ddff0000cf9f5f00c85f9f00fa00ff00fa"},
        {0x87eeU, "00fafa8888c6fa00e08300f8e4e4e4e4", "0000003200ff00ff00ff0064ff0000960000000000ff00fa00ff0032ff0000960000000000ff000000ff0064ff0000c8000000ff00ff00fa00ff0000ff000000"},
    };
    for (const auto& v : vectors) {
        CAPTURE(v.format); CAPTURE(v.input);
        CHECK(ogplay::gles::DecodeAtcRgba8(4,4,v.format,Hex(v.input)) == Hex(v.rgba));
    }
}
TEST_CASE("ATC decoder clips blocks and bounds image allocations") {
    using namespace ogplay::gles;
    const auto block = Hex("007ce007e4e4e4e4");
    const auto full = DecodeAtcRgba8(4,4,kAtcRgb,block);
    const auto edge = DecodeAtcRgba8(3,2,kAtcRgb,block);
    REQUIRE(edge.size()==24U);
    for (std::size_t y=0;y<2;++y)for(std::size_t x=0;x<3;++x)
        for(std::size_t c=0;c<4;++c) CHECK(edge[(y*3+x)*4+c]==full[(y*4+x)*4+c]);
    auto two = block;two.insert(two.end(),block.begin(),block.end());
    CHECK(DecodeAtcRgba8(5,4,kAtcRgb,two).size()==80U);
    CHECK(DecodeAtcRgba8(0,0,kAtcRgb,{}).empty());
    CHECK_THROWS_AS(static_cast<void>(DecodeAtcRgba8(4,4,kAtcRgb,std::span(block).first(7))),std::invalid_argument);
    CHECK_THROWS_AS(static_cast<void>(AtcImageBytes(4,4,0)),std::invalid_argument);
    CHECK_THROWS_AS(static_cast<void>(AtcImageBytes(UINT32_MAX,UINT32_MAX,kAtcRgbaExplicit)),std::length_error);
    // Correct compressed size, but RGBA8 would exceed the 64 MiB decode budget.
    std::vector<std::byte> large(AtcImageBytes(8192,4096,kAtcRgb));
    CHECK_THROWS_AS(static_cast<void>(DecodeAtcRgba8(8192,4096,kAtcRgb,large)),std::length_error);
}
